#pragma config(Sensor, in1,    IR_Sensor,      sensorAnalog)
#pragma config(Sensor, in2,    UItraSonicSensor, sensorAnalog)
#pragma config(Sensor, dgtl3,  ButtonOne,      sensorTouch)
#pragma config(Sensor, dgtl4,  ButtonTwo,      sensorTouch)
#pragma config(Motor,  port1,           RightMotor,    tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           LeftMotor,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           DroppingMotor, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void turn3Left(){

		motor[RightMotor] = 55;
		motor[LeftMotor] = -40;

		wait1Msec(39);//Adjust time so that its perfect

		motor[RightMotor] = 0;
		motor[LeftMotor] = 0;

	}

	void turn3Right(){

		motor[RightMotor] = -40;
		motor[LeftMotor] = 40;

		wait1Msec(47);//Adjust time so that its perfect

		motor[RightMotor] = 0;
		motor[LeftMotor] = 0;

	}

void moveBackwards20(){

	//motor[DroppingMotor] = 80;

	motor[RightMotor] = -40;
	motor[LeftMotor] = -40;

	wait1Msec(1500);//Adjust time so that its perfect

	motor[RightMotor] = 0;
	motor[LeftMotor] = 0;

}

void moveForward3(){

		motor[RightMotor] = 30;
		motor[LeftMotor] = 30;

		wait1Msec(800);//Adjust time so that its perfect

		motor[RightMotor] = 0;
		motor[LeftMotor] = 0;

	}

void turn60Degrees(){

		motor[RightMotor] = -40;
		motor[LeftMotor] = 40;

		wait1Msec(1000);//Adjust time so that its perfect

		motor[RightMotor] = 0;
		motor[LeftMotor] = 0;
}

void turn30DegreesRight(){

		motor[RightMotor] = -40;
		motor[LeftMotor] = 40;

		wait1Msec(560);//Adjust time so that its perfect

		motor[RightMotor] = 0;
		motor[LeftMotor] = 0;
}


void turn20DegreesRight(){

		motor[RightMotor] = -40;
		motor[LeftMotor] = 40;

		wait1Msec(400);//Adjust time so that its perfect

		motor[RightMotor] = 0;
		motor[LeftMotor] = 0;
}


int SecondaryScan(){

	int minIRValue = 9999999;

	int i = 0;

	turn30DegreesRight();

	int value1 = 99999;
	int value2 = 99999;
	int finalDegreesToRotate = 30;

	while(i < 80){

		value1 = SensorValue(IR_Sensor);

		wait1Msec(60);

		value2 = SensorValue(IR_Sensor);

		if(value1 < minIRValue){

			minIRValue = value1;
			finalDegreesToRotate = 80 - i;
		}

		if(value2 < value1 && value2 < minIRValue){

			minIRValue = value2;
			finalDegreesToRotate = 80 - i;

		}


		turn3Left();

		i = i + 3;

	}

	return finalDegreesToRotate;

}

int finalTurn(){

	int smallestDistance = 500;
	int i = 0;
	int finalDegreesToTurn = 0;

	turn20DegreesRight();

	while(i < 40){
		turn3Left();

		wait1Msec(10);

		if(SensorValue[UltraSonicSensor] < smallestDistance){
			smallestDistance = SensorValue[UltraSonicSensor];
			finalDegreesToTurn = 40 - i;

		}

			i = i + 3;
	}

	return finalDegreesToTurn;
}












void dropBall(){

		motor[DroppingMotor] = 80;

		wait1Msec(300);

		motor[DroppingMotor] = 0;

		//wait1Msec(3000);

		//motor[DroppingMotor] = -18;

		//wait1Msec(350);

		//motor[DroppingMotor] = 0;
	}


task main(){

	int i = 0;
	int value1 = 0;
	int value2 = 0;
	int j = 0;
	int increase = 27;
	//SensorValue[redLight] = 0;
	int q = 0;
	int minIRValue = 999999;
	int finalDegreesToRotate = 0;
	int pleaseWork = 0;
	int www = 0;
	int Sadd = 0;
	int Quinn = 0;



	while(1){

	//Once ButtonOne is pressed it will enter this if statement

		if(SensorValue(ButtonOne) == 1){

			j = 1;

			while(i < 322){

				value1 = SensorValue(IR_Sensor);

				wait1Msec(60);

				value2 = SensorValue(IR_Sensor);

				if(value1 < minIRValue){

					minIRValue = value1;

					finalDegreesToRotate = i;

				}

				if(value2 < minIRValue){

					minIRValue = value2;

					finalDegreesToRotate = i;

				}



				turn3Left();

				i = i + 3;

			}

			writeDebugStream("minIRValue is %d  ", minIRValue);

			writeDebugStream("finalDegreesToRotate is %d  ", finalDegreesToRotate);

			int clay = 0;

			while(clay < finalDegreesToRotate + 2){

				turn3Left();

				clay = clay + 3;
			}



			if(j == 1){

				while(SensorValue[UltraSonicSensor] > 18){

					moveForward3();

					if(SensorValue[UltraSonicSensor] < 18){

						motor[RightMotor] = 0;
						motor[LeftMotor] = 0;

						break;
					}

					moveForward3();

					if(SensorValue[UltraSonicSensor] < 18){

						motor[RightMotor] = 0;
						motor[LeftMotor] = 0;

						break;
					}

					pleaseWork = SecondaryScan();



					while(www <= pleaseWork){
						turn3Right();
						www = www + 3;
					}
					www = 0;

				}


				int Sadd = finalTurn();

				int Quinn = 0;

				while(Quinn <= Sadd){
					turn3Right();
					Quinn = Quinn + 3;
				}

				dropBall();

				wait1Msec(2000);

				moveBackwards20();

				motor[DroppingMotor] = 80;

				wait1Msec(5000);


				wait1Msec(99999);


			}
		}
	}
}



